name: Generate Snake Game Animation

on:
  schedule:
    - cron: '0 0 */1 * *'  # Runs at midnight every day
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches:
      - master  # Runs on every push to the master branch

jobs:
  generate:
    permissions:
      contents: write  # Grants permission to write to the repository contents
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Generate snake game from GitHub contribution grid
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      - name: Push generated SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Specifies the branch to which the files will be pushed
          build_dir: dist  # The directory where the generated SVG files are located
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Uses the GITHUB_TOKEN for authentication
